### ISSUE TITLE
Get groups 

### ISSUE THREAD

**Issue by mathildegui** [getsenic/lifx-sdk-android#1]
Hi,

is there a way to get the groups with the SDK ? 

Thanks
Mathilde

**Comment by auras** [comment]
Hey,
It's planned but no specific timeline yet.

The only issue is I don't know what you can do with them except displaying them. There's nothing documented in the protocol about using the groups.

**Comment by mathildegui** [comment]
Well I do want to display them :) 
After that I would like to controls lights by group. Switch them all off or on for instance

**Comment by mathildegui** [comment]
Hi here, 

I have tried to do it then ... :) But I think something wrong. Well if you can take a look it will be great.
Here the two commits concerned:
[First one](https://github.com/mathildegui/lifx-sdk-android-1/commit/eb923747acf955614a7c6a48895fa11bfc45dc12)
[Second one](https://github.com/mathildegui/lifx-sdk-android-1/commit/cdc9cc0ae5e56c1a5af6d41f9831990d3586be9c)

So I try to call getGroup() on a LFXLight object by I always get null value .. Hope you'll could help :)

Thanks by advance
Mathilde

**Comment by auras** [comment]
You have to debug it to see where it's failing. I would start with LFXLight.java and see what's inside `message `and `message.getPayload()` in `handleMessage(LFXMessage message)`

I'll try tomorrow to see if it works for me

**Comment by auras** [comment]
Se the latest commits, seems to be working for me.

**Comment by mathildegui** [comment]
Hi,

have you tested it ? So it's working on your side for the groups ?

**Comment by auras** [comment]
That's right.

**Comment by larsblumberg** [comment]
@mathildegui: Does getting the light group work for you?

**Comment by mathildegui** [comment]
Hi @larsblumberg,

I have updated your sdk with the last version. It is working now. Thanks !

**Comment by larsblumberg** [comment]
@mathildegui – Great, thanks for your feedback.
