### ISSUE TITLE
Unable to control lights without connected to Wifi in my smartphone

### ISSUE THREAD

**Issue by krishnestlifx** [getsenic/lifx-sdk-android#3]
Hi Sir,

I need to connect to Lifx bulb color 1000 in wifi settings then only I'm able to control its powerstate. But, I need to connect to a network in wifi in order to control thermostat using Nest API. If I connect to Lifx bulb under wifi then I'm unable to use Nest API.

Basically I should have both the functionalities. My requirement is when user sets to Away profile then I should turn on bulb. similarly if user sets Home profile I should turn off lights.

I tried this  approach but no luck. I configured the Lifx bulb in the default Lifx playstore app. I am unable to connect to wifi there directly. It is launching wifi settings screen there I need to choose the bulb to connect. If I switch the wifi network to my regular network then I'm unable to control the light.

Is there any solution to achieve the above said two functionalities together. Please help me with the possible solutions.

**Comment by larsblumberg** [comment]
Dear @krishnestlifx, if you use this LIFX SDK, your phone needs to be connected to the Wi-Fi where your LIFX lights are connected to. Besides that, I can't give you any further support for your questions. Please contact LIFX directly.
