### ISSUE TITLE
Possible to use this in eclipse?

### ISSUE THREAD

**Issue by ThomasWrobel** [getsenic/lifx-sdk-android#4]
1. Thank you for this existing. 
2. Trying to update a old Android project I had of mine to be compatible with the newer lightbulb firmware.
The project is setup in eclipse, and I am not keen to change to Android Studio unless I really have too. The project itself does not make use of Gradle, although my eclipse does have a gradle plugin installed that has worked for other projects. 

I checked out lifx-sdk-android and used that gradle plugin to import into eclipse. It resulted in two packages appearing called;
#
>Library
>Lifx-sdk-android.git

It also gives me lots of Gradle tasks listed for both of them.

However, neither of these packages is recognized as a Android project. Normally if they were I would tick a little "is library" box and then I could set my own project to use that library.
As I cant do that I am at a loss how to proceed.

I did add;
 `   <uses-library android:name="lifx.java.android" />`
To my manifest in case it helped, but it didn't seem to.

Any ideas/pointers? Do I need to run one of those gradle tasks?

**Comment by ThomasWrobel** [comment]
Ok, just adding it as a project on the build path worked anyway. Doesn't seem to care its not recognized as Android. After a refresh/build/compile bulbs are all picked up fine.

**Comment by larsblumberg** [comment]
👍
